kind = "web"
previewPath = "/"
title = "Sistem Kamar Bedah - RS Panti Rini"
version = "1.0.0"
id = "artifacts/kamar-bedah"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24074

[services.development]
run = "pnpm --filter @workspace/kamar-bedah run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/kamar-bedah", "run", "build" ]
publicDir = "artifacts/kamar-bedah/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24074"
BASE_PATH = "/"
